config/routes.rb
Rails.application.routes.draw do
  resources :freezers
  root to: 'freezers#index'
end

app/models/freezer.rb
class Freezer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/freezers_controller.rb
class FreezersController < ApplicationController
  before_action :set_freezer, only: [:show, :edit, :update, :destroy]

  # GET /freezers
  # GET /freezers.json
  def index
    @freezers = Freezer.all
  end

  # GET /freezers/1
  # GET /freezers/1.json
  def show
  end

  # GET /freezers/new
  def new
    @freezer = Freezer.new
  end

  # GET /freezers/1/edit
  def edit
  end

  # POST /freezers
  # POST /freezers.json
  def create
    @freezer = Freezer.new(freezer_params)

    respond_to do |format|
      if @freezer.save
        format.html { redirect_to @freezer, notice: 'Freezer was successfully created.' }
        format.json { render :show, status: :created, location: @freezer }
      else
        format.html { render :new }
        format.json { render json: @freezer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /freezers/1
  # PATCH/PUT /freezers/1.json
  def update
    respond_to do |format|
      if @freezer.update(freezer_params)
        format.html { redirect_to @freezer, notice: 'Freezer was successfully updated.' }
        format.json { render :show, status: :ok, location: @freezer }
      else
        format.html { render :edit }
        format.json { render json: @freezer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /freezers/1
  # DELETE /freezers/1.json
  def destroy
    @freezer.destroy
    respond_to do |format|
      format.html { redirect_to freezers_url, notice: 'Freezer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_freezer
      @freezer = Freezer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def freezer_params
      params.require(:freezer).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/freezers_helper.rb
module FreezersHelper
end

app/views/freezers/_form.html.erb
<%= form_for(@freezer) do |f| %>
  <% if @freezer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@freezer.errors.count, "error") %> prohibited this freezer from being saved:</h2>

      <ul>
      <% @freezer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/freezers/edit.html.erb
<h1>Editing Freezer</h1>

<%= render 'form' %>

<%= link_to 'Show', @freezer %> |
<%= link_to 'Back', freezers_path %>

app/views/freezers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Freezers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @freezers.each do |freezer| %>
      <tr>
        <td><%= link_to freezer.name, freezer %></td>
        <td><%= link_to 'Edit', edit_freezer_path(freezer) %></td>
        <td><%= link_to 'Destroy', freezer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Freezer', new_freezer_path %>

app/views/freezers/new.html.erb
<h1>New Freezer</h1>

<%= render 'form' %>

<%= link_to 'Back', freezers_path %>

app/views/freezers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @freezer.name %>
</p>

<%= link_to 'Edit', edit_freezer_path(@freezer) %> |
<%= link_to 'Back', freezers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FreezerTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>